# Travis configuration

language: python
python: 2.7

dist: trusty
sudo: false

services:
  - docker

env:
  - DOCKER_TAG=honeysap:development

install:
  - pip2 install .
  - pip2 install flake8
  - pip2 install -r requirements-docs.txt

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  - docker build -t ${DOCKER_TAG} -f deployment/Dockerfile .

script:
  - python setup.py test
  - python setup.py doc
  - docker images ${DOCKER_TAG}

after_script:
  - docker rmi ${DOCKER_TAG}

before_deploy:
  # Build a source and wheel artifact
  - python setup.py sdist
  - python setup.py bdist_wheel
